In [9]:
import pandas as pd 

df_historical_data = pd.read_csv("euro_historical_data.csv")
df_fixture = pd.read_csv("euro_2024_fixtures.csv")

# Erase the unnecessary space in the Home and Away columns
df_fixture["Home"] = df_fixture["Home"].str.strip()
df_fixture["Away"] = df_fixture["Away"].str.strip()

# Delete (a.e.t) in the Score column
df_historical_data["Score"] = df_historical_data["Score"].str.replace(r"\(.*\)", "", regex=True).str.strip()
df_historical_data["Home"] = df_historical_data["Home"].str.strip()
df_historical_data["Away"] = df_historical_data["Away"].str.strip()

import pandas as pd 

# Read the CSV files
df_historical_data = pd.read_csv("euro_historical_data.csv")
df_fixture = pd.read_csv("euro_2024_fixtures.csv")

# Erase the unnecessary space in the Home and Away columns
df_fixture["Home"] = df_fixture["Home"].str.strip()
df_fixture["Away"] = df_fixture["Away"].str.strip()

# Clean up the Score, Home, and Away columns in the historical data
df_historical_data["Score"] = df_historical_data["Score"].str.replace(r"\(.*\)", "", regex=True).str.strip()
df_historical_data["Home"] = df_historical_data["Home"].str.strip()
df_historical_data["Away"] = df_historical_data["Away"].str.strip()

# Extract only the numeric scores from the Score column
score_pattern = r"(\d+)[–-](\d+)"  # Regex to match scores like "2-1" or "2–1"
scores = df_historical_data["Score"].str.extract(score_pattern)

# Assign the extracted scores to new columns and convert to integers
df_historical_data["HomeGoals"] = scores[0].astype(float).astype(int)
df_historical_data["AwayGoals"] = scores[1].astype(float).astype(int)

# Delete the score column
df_historical_data.drop("Score", axis=1, inplace=True)
df_historical_data.rename(columns={"Home" : "HomeTeam", "Away" : "AwayTeam"}, inplace=True)


# Create a total goals column
df_historical_data["TotalGoals"] = df_historical_data["HomeGoals"] + df_historical_data["AwayGoals"]


df_historical_data.to_csv("clean_euro_historical_data.csv", index=False)
df_fixture.to_csv("clean_euro_2024_fixtures.csv", index=False)

years = [1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020]

allMatches = 0

for year in years:
    allMatches += len(df_historical_data[df_historical_data["Year"]==year])

print(allMatches)

df_historical_data

337

           HomeTeam      AwayTeam  Year  HomeGoals  AwayGoals  TotalGoals
0            France    Yugoslavia  1960          4          5           9
1    Czechoslovakia  Soviet Union  1960          0          3           3
2    Czechoslovakia        France  1960          2          0           2
3      Soviet Union    Yugoslavia  1960          2          1           3
4             Spain       Hungary  1964          2          1           3
..              ...           ...   ...        ...        ...         ...
332  Czech Republic       Denmark  2020          1          2           3
333         Ukraine       England  2020          0          4           4
334           Italy         Spain  2020          1          1           2
335         England       Denmark  2020          2          1           3
336           Italy       England  2020          1          1           2

[337 rows x 6 columns]